
import type { Question } from './types';

export const DECISION_MAKING_QUESTIONS: Question[] = [
  {
    id: 'dm_q1',
    type: 'YesNoStatements',
    section: 'Decision Making',
    stimulus: 'Premises:\nNo reptile is a mammal.\nAll pythons are reptiles.\nSome reptiles are kept as pets.',
    questionText: 'Question 1\nConclusions: For each statement, indicate if it logically follows from the premises.',
    conclusions: [
      { id: 'dm_q1_s1', text: 'Nobody kept as a pet is a python.' },
      { id: 'dm_q1_s2', text: 'No python is a mammal.' },
      { id: 'dm_q1_s3', text: 'If an animal has no wings, it cannot be a whiffle.' },
      { id: 'dm_q1_s4', text: 'An animal that is a mammal cannot be kept as a pet.' },
      { id: 'dm_q1_s5', text: 'An animal that is not a python cannot be a mammal.' },
    ],
    correctAnswer: {
      'dm_q1_s1': 'yes',
      'dm_q1_s2': 'no',
      'dm_q1_s3': 'no',
      'dm_q1_s4': 'no',
      'dm_q1_s5': 'yes',
    },
    explanation: 'Evaluate each conclusion based *only* on the given premises.',
  },
  {
    id: 'dm_q2',
    type: 'YesNoStatements',
    section: 'Decision Making',
    stimulus: 'Premises:\nWhiffles and sparrows are animals, but neither has scales, although both have wings.\nA flarn has wings but is not a sparrow.',
    questionText: 'Question 2\nConclusions: For each statement, indicate if it logically follows from the premises.',
    conclusions: [
      { id: 'dm_q2_s1', text: 'Flarns do not have scales.' },
      { id: 'dm_q2_s2', text: 'Flarns are animals.' },
      { id: 'dm_q2_s3', text: 'Either sparrows or flarns have scales.' },
      { id: 'dm_q2_s4', text: 'If an animal has no wings, it cannot be a whiffle.' },
      { id: 'dm_q2_s5', text: 'If an animal is a flarn, it cannot be a sparrow.' },
    ],
    correctAnswer: {
      'dm_q2_s1': 'no',
      'dm_q2_s2': 'no',
      'dm_q2_s3': 'no',
      'dm_q2_s4': 'yes',
      'dm_q2_s5': 'yes',
    },
    explanation: 'Evaluate each conclusion based *only* on the given premises.',
  },
  {
    id: 'dm_q3',
    type: 'YesNoStatements',
    section: 'Decision Making',
    stimulus: 'Premises:\nThe bookstore received the same number of hard-cover, paperback, and audio-book copies of a new title. On one particular day:\nIt sold twice as many paperbacks as hard-covers, and\nIt sold exactly as many audio-books as hard-covers and paperbacks combined.',
    questionText: 'Question 3\nConclusions: For each statement, indicate if it logically follows from the premises.',
    conclusions: [
      { id: 'dm_q3_s1', text: 'A quarter of all sales that day were hard-cover copies.' },
      { id: 'dm_q3_s2', text: 'By closing time the store had fewer paperbacks left in stock than hard-covers.' },
      { id: 'dm_q3_s3', text: 'Hard-cover copies were less popular with customers than audio-books.' },
      { id: 'dm_q3_s4', text: 'If, on the following day, the store doubled the number of hard-covers sold while selling the same number of paperbacks, it would have sold more hard-covers than paperbacks.' },
      { id: 'dm_q3_s5', text: 'Exactly one-third of all the copies originally stocked were audio-books.' },
    ],
    correctAnswer: {
      'dm_q3_s1': 'yes',
      'dm_q3_s2': 'no',
      'dm_q3_s3': 'no',
      'dm_q3_s4': 'yes',
      'dm_q3_s5': 'yes',
    },
    explanation: 'Evaluate each conclusion based *only* on the given premises.',
  },
  {
    id: 'dm_q4',
    type: 'YesNoStatements',
    section: 'Decision Making',
    stimulus: 'Premises:\nInside the suitcase were some green hats, some yellow hats, but only a few purple hats.\nThere was nothing else in the suitcase except for some black gloves and a few purple gloves.',
    questionText: 'Question 4\nConclusions: For each statement, indicate if it logically follows from the premises.',
    conclusions: [
      { id: 'dm_q4_s1', text: 'If you took out a purple item, it would be a hat.' },
      { id: 'dm_q4_s2', text: 'As well as purple and black items, the suitcase also contained some yellow items.' },
      { id: 'dm_q4_s3', text: 'There were no black garments in the suitcase.' },
      { id: 'dm_q4_s4', text: 'There were more purple garments than green garments in the suitcase.' },
      { id: 'dm_q4_s5', text: 'The only yellow garments were hats.' },
    ],
    correctAnswer: {
      'dm_q4_s1': 'no',
      'dm_q4_s2': 'yes',
      'dm_q4_s3': 'yes',
      'dm_q4_s4': 'yes',
      'dm_q4_s5': 'no',
    },
    explanation: 'Evaluate each conclusion based *only* on the given premises. Note: Interpretation of "garments" can be key.',
  },
  {
    id: 'dm_q5',
    type: 'YesNoStatements',
    section: 'Decision Making',
    stimulus: 'Premises:\nZephyrs and kites are types of aircraft.\nAll zephyrs are aeros.\nOnly the aeros that fly over the Atlantic carry radar.\nAll aeros are blue.',
    questionText: 'Question 5\nConclusions: For each statement, indicate if it logically follows from the premises.',
    conclusions: [
      { id: 'dm_q5_s1', text: 'Zephyrs are blue.' },
      { id: 'dm_q5_s2', text: 'All aircraft are aeros.' },
      { id: 'dm_q5_s3', text: 'Neither zephyrs nor kites fly over the Atlantic.' },
      { id: 'dm_q5_s4', text: 'If an aero carries radar, it must fly over the Atlantic.' },
      { id: 'dm_q5_s5', text: 'Not all blue aeros carry radar.' },
    ],
    correctAnswer: {
      'dm_q5_s1': 'no',
      'dm_q5_s2': 'yes',
      'dm_q5_s3': 'no',
      'dm_q5_s4': 'yes',
      'dm_q5_s5': 'no',
    },
    explanation: 'Evaluate each conclusion based *only* on the given premises.',
  },
  {
    id: 'dm_q6',
    type: 'YesNoStatements',
    section: 'Decision Making',
    stimulus: 'Premises:\nIn Maria’s fruit bowl, there are green apples and there are peaches.\nNothing else is in the bowl except for the yellow bananas.',
    questionText: 'Question 6\nConclusions: For each statement, indicate if it logically follows from the premises.',
    conclusions: [
      { id: 'dm_q6_s1', text: 'Some of the fruit is red.' },
      { id: 'dm_q6_s2', text: 'There are some green fruits.' },
      { id: 'dm_q6_s3', text: 'There are no yellow fruits.' },
      { id: 'dm_q6_s4', text: 'There are no red bananas.' },
      { id: 'dm_q6_s5', text: 'All of the fruit is either green or yellow.' },
    ],
    correctAnswer: {
      'dm_q6_s1': 'no',
      'dm_q6_s2': 'yes',
      'dm_q6_s3': 'no',
      'dm_q6_s4': 'yes',
      'dm_q6_s5': 'no',
    },
    explanation: 'Evaluate each conclusion based *only* on the given premises.',
  },
  {
    id: 'dm_q7',
    type: 'MCQ',
    section: 'Decision Making',
    stimulus: 'Lina has copper (C), aluminium (A) and steel (S) rods. All rods of the same metal weigh the same. A bundle containing 2 copper + 3 aluminium + 1 steel rod weighs 70 kg. A bundle containing 1 copper + 2 aluminium + 1 steel rod weighs 40 kg.',
    questionText: 'Question 7\nWhat is most likely the weight of a bundle containing 4 copper rods, 4 aluminium rods and 1 steel rod?',
    options: [
      { id: 'dm_q7_o1', text: '120kg' },
      { id: 'dm_q7_o2', text: '128kg' },
      { id: 'dm_q7_o3', text: '160kg' },
      { id: 'dm_q7_o4', text: '176kg' },
    ],
    correctAnswer: 'dm_q7_o2', // B is 128kg
    explanation: 'Let C, A, S be the weights. 2C+3A+S=70, C+2A+S=40. Subtracting: C+A=30. We need 4C+4A+S. 4(C+A)+S = 4(30)+S = 120+S. From C+2A+S=40 => 30-A+2A+S=40 => 30+A+S=40 => A+S=10. S=10-A. We know C=30-A. Original: 2(30-A)+3A+(10-A) = 60-2A+3A+10-A = 70. 70=70. This implies the system has multiple solutions for individual A, C, S. If A=10, C=20, S=0. Then 4C+4A+S = 4(20)+4(10)+0 = 80+40=120. If A=0, C=30, S=10. Then 4C+4A+S = 4(30)+4(0)+10 = 120+10 = 130. The question asks for "most likely". Let\'s check the option 128kg. We need 120+S = 128, so S=8kg. If S=8, A+S=10 => A=2kg. C+A=30 => C=28kg. Check original equations: 2(28)+3(2)+8 = 56+6+8 = 70 (Correct). 1(28)+2(2)+8 = 28+4+8 = 40 (Correct). So C=28, A=2, S=8 is a valid solution. The target bundle is 4C+4A+S = 4(28)+4(2)+8 = 112+8+8 = 128kg.',
  },
  {
    id: 'dm_q8',
    type: 'MCQ',
    section: 'Decision Making',
    stimulus: 'There are six folders stacked in a tray, numbered 1 (top) to 6 (bottom).\nZoe’s folder is not the bottom-most folder (not 6).\nThe number of folders below Zoe’s folder is less than the number above it.\nEthan’s folder is the last-but-one folder from the bottom of the stack (position 5).\nThere are exactly two folders between Maya’s folder and Zoe’s folder.\nLiam’s folder is not above Zoe’s folder (Liam <= Zoe in position number, or Liam is below or same as Zoe).',
    questionText: 'Question 8\nHow many folders are there between Maya’s folder and Liam’s folder?',
    options: [
      { id: 'dm_q8_o1', text: '1' },
      { id: 'dm_q8_o2', text: '2' },
      { id: 'dm_q8_o3', text: '3' },
      { id: 'dm_q8_o4', text: '4' },
    ],
    correctAnswer: 'dm_q8_o4', // 4 folders
    explanation: 'Let Z, E, M, L be positions. Folders 1(top) to 6(bottom).\n1. Z != 6.\n2. (6-Z) < (Z-1). E.g., if Z=2, below=4, above=1. (4 < 1 false). If Z=3, below=3, above=2. (3 < 2 false). If Z=4, below=2, above=3 (2 < 3 true). If Z=5, below=1, above=4 (1 < 4 true). So Z can be 4 or 5.\n3. E = 5.\nFrom (2) and (3), if Z=5, this means E=Z. This is possible. (6-5=1) < (5-1=4) is true. So Z=5 or Z=4.\n4. |M - Z| - 1 = 2 => |M - Z| = 3. So M and Z are 3 positions apart.\n   If Z=4: M=1 or M=7(invalid). So M=1.\n   If Z=5: M=2 or M=8(invalid). So M=2.\n5. Liam is not above Zoe: L >= Z (position number). L can be Z.\nCase 1: Z=4, M=1, E=5.\n   L >= 4. Possible L: 4, 5, 6. (E=5, Z=4, M=1). If L=4 (Zoe and Liam are same folder, question implies distinct people). If L=5 (E and L same). If L=6. Liam folder is L.\n   If L=4, folders between M(1) and L(4) are 2,3. Number of folders = 2.\n   If L=6, folders between M(1) and L(6) are 2,3,4,5. Number of folders = 4.\nCase 2: Z=5, M=2, E=5.\n   Here Z=E=5. (This might be an issue if Zoe and Ethan are different people, usually assumed unless stated otherwise).\n   L >= 5. Possible L: 5, 6.\n   If L=5 (Z, E, L are same folder). Folders between M(2) and L(5) are 3,4. Number of folders = 2.\n   If L=6. Folders between M(2) and L(6) are 3,4,5. Number of folders = 3.\nRe-evaluating "Zoe’s folder is not the bottom-most folder": Z != 6. "The number of folders below Zoe’s folder is less than the number above it": (Num Below = 6-Z), (Num Above = Z-1). So, 6-Z < Z-1 => 7 < 2Z => Z > 3.5. So Z can be 4 or 5.\nEthan E=5.\nIf Z=4: Below=2, Above=3. (2<3 True). M is such that |M-4|=3. So M=1 or M=7. M=1.\n   Liam L >= Z, so L>=4. L can be 4, 5, 6. Folders are (1:M, 2:_, 3:_, 4:Z, 5:E, 6:_). If L=4(Z), between M(1) and L(4) are 2,3 (2 folders). If L=5(E), between M(1) and L(5) are 2,3,4 (3 folders). If L=6, between M(1) and L(6) are 2,3,4,5 (4 folders).\nIf Z=5: Below=1, Above=4. (1<4 True). M is such that |M-5|=3. So M=2 or M=8. M=2.\n   Liam L >= Z, so L>=5. L can be 5, 6. Folders are (1:_, 2:M, 3:_, 4:_, 5:Z/E, 6:_). If L=5(Z/E), between M(2) and L(5) are 3,4 (2 folders). If L=6, between M(2) and L(6) are 3,4,5 (3 folders).\nThe answer options are 1,2,3,4. The answer key is 4. This implies Z=4, M=1, E=5, L=6. This combination is consistent with all rules. Folders between M(1) and L(6) are 2,3,4,5. Count is 4. This scenario: Maya(1), _, _, Zoe(4), Ethan(5), Liam(6). This fits all conditions.',
  },
];

// Keeping UCAT_QUESTIONS for now to avoid breaking imports in page.tsx,
// but it should be replaced by DECISION_MAKING_QUESTIONS.
// For this change, we'll assume page.tsx will be updated to use DECISION_MAKING_QUESTIONS.
export const UCAT_QUESTIONS = DECISION_MAKING_QUESTIONS;
